### ISSUE TITLE
Elytra Glitch

### ISSUE THREAD

**Issue by cococow123** [Guichaguri/BetterFps#13]
Hello Guichaguri.

I have found a glitch/bug in the MC 1.10.2 version with Elytra (Haven't tried any other versions):

[Single Player] When I look straight up and activate Elytra, I fall through the world a little and MC stops responding 

[Spigot Multiplayer Server] When I look straight up and activate Elytra, I fall through the floor all the way to the void. When I TP to myself (/tp) My coords are "NaN / (Y is same) / NaN".

Also, my arms and legs have dissapeared! Note: I have not tested this in a regular server.

Images: http://imgur.com/a/zHXpy

 _Algorithm: Riven's Half_

Thanks,

Coco

**Comment by SharkWipf** [comment]
As explained in the referenced issue above, I'm not experiencing this bug with the regular Elytra (anymore?), but the EnderIO dark plate Elytra still seems to suffer from it with Riven's Half algorithm. 
I was going to wait for a reply in the EnderIO issue before adding more info here, but then issue #22 wouldn't make much sense anymore,

EDIT: 
BetterFps: BetterFps-1.3.2
Minecraft: 1.10.2
Forge: forge-1.10.2-12.18.3.2185-universal
EnderIO: EnderIO-1.10.2-3.0.1.149_beta
EnderCore: EnderCore-1.10.2-0.4.1.62-beta
Modpack: [Blockheadism](https://minecraft.curseforge.com/projects/blockheadism)

**Comment by Guichaguri** [comment]
Fixed it. A new release will come once I finish fixing the bugs :)

But I have to say, that was a pretty interesting bug, the whole collision engine was disabled because the algorithm was returning the wrong angle

**Comment by cococow123** [comment]
Awesome! Thanks for checking it out 😀👍

**Comment by SharkWipf** [comment]
Great, that was quick. 
Yeah, it's a pretty interesting bug, even more so because it still happened on the client side even if you switched the server to another algorithm. Would expect the server to go "hey, you're noclipping, stop that!"
Thanks a lot for the fix!
