### ISSUE TITLE
There should be an option to change the location of the BetterFPS options button to the left

### ISSUE THREAD

**Issue by Sunconure11** [Guichaguri/BetterFps#56]
The option should be in game, too, as to help avoid some conflicts with mods that use that spot. Xaero's Minimap minimap options are in the same location in the options panel, for instance.

**Comment by Guichaguri** [comment]
Which version are you using? I think I fixed it before.
Related to #36

**Comment by Sunconure11** [comment]
v1.4.3-1.10

**Comment by Sunconure11** [comment]
This issue happens on servers only

**Comment by Guichaguri** [comment]
?
You mean when connected into a server?

**Comment by Sunconure11** [comment]
Yes.

If it is of any relevance, BetterFPS is on the server too.

**Comment by Guichaguri** [comment]
I've just released a [new version](https://minecraft.curseforge.com/projects/betterfps/files/2415911). Can you try it out?

**Comment by Sunconure11** [comment]
Issue still persists.

This is happening on 1.10.2, and the server also has the mod installed (though Xaero's is not installed to the server)

**Comment by Sunconure11** [comment]
If it helps, the server is using Sponge.

**Comment by Guichaguri** [comment]
This is purely client-side, you can even open the options screen in the menu screen.

![Options Screen](https://i.imgur.com/74vZuCc.png)

It's working as expected for me. I'm using BetterFps 1.4.4-1.10, Xaero's Minimap 1.12.8, Forge 2185 on Minecraft 1.10.2

**Comment by Guichaguri** [comment]
I can't reproduce the problem, so I'll be closing this issue, feel free to reopen it if you can provide more information :P

**Comment by Sunconure11** [comment]
Yeah, its probably due to the fact that one cannot put Xaero's Minimap on a server. Maybe add a config option to change the location anyways?

**Comment by Guichaguri** [comment]
This is all client-side, using both mods in a server or not should make no difference.
In my tests I was using both mods in the client, both in singleplayer (which counts as having both mods in the server) and in a vanilla server

**Comment by Sunconure11** [comment]
Weird.
